"""making file hash and error message nullable

Revision ID: 35be7e112fc3
Revises: d436ca3bc544
Create Date: 2026-08-02 10:02:07.476736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35be7e112fc3'
down_revision: Union[str, Sequence[str], None] = 'd436ca3bc544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice_jobs', 'file_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('invoice_jobs', 'error_message',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice_jobs', 'error_message',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('invoice_jobs', 'file_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
