"""making other fields nullabel too.

Revision ID: 92b1cfd7e6d8
Revises: 036a36d5c694
Create Date: 2026-08-02 10:56:01.567578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92b1cfd7e6d8'
down_revision: Union[str, Sequence[str], None] = '036a36d5c694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'vendor_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('invoices', 'invoice_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('invoices', 'warnings',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    op.alter_column('invoices', 'issues',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'issues',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    op.alter_column('invoices', 'warnings',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('invoices', 'invoice_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('invoices', 'vendor_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
